### ISSUE TITLE
json接口返回时间晚了8小时

### ISSUE THREAD

**Issue by menghuanbiao** [zchuanzhao/jeesns#4]
jackson 引发的中国区的bug，需要在spring mvc的工程配置文件中 配置下随系统时间区域

**Comment by zchuanzhao** [comment]
请问你这边是什么环境呢？我这边用win7、jdk8、tomcat7测试是正常的

**Comment by zchuanzhao** [comment]
一个网站使用linux系统会差8个小时，已经指定时区，代码已提交
