### ISSUE TITLE
反射型xss

### ISSUE THREAD

**Issue by 360CodeSafe** [zchuanzhao/jeesns#8]
您好：
    我是360代码卫士的工作人员，在我们的开源项目的代码审计中发现jeesns存在xss漏洞，详细信息如下：
    在CkeditorUploadController.java文件的32行处获取了请求中的CKEditorFuncNum参数，最后在41行处输出在页面上导致了xss漏洞。
![default](https://user-images.githubusercontent.com/39950310/50393679-c8620f00-0792-11e9-9c1e-330857ede754.png)
    虽然项目中存在xss拦截器
![default](https://user-images.githubusercontent.com/39950310/50393695-e760a100-0792-11e9-980d-027e86e86504.png)
但是由于只对script标签内的字符做了过滤，而此处的xss并不需要利用script标签，因为上下文中已经有了。CKEditorFuncNum=");prompt(1);

虽然是post请求的反射型xss，但是还是能结合csrf进行攻击

**Comment by zchuanzhao** [comment]
已处理，多谢
